import type { MD3Theme } from 'react-native-paper';
import { MD3DarkTheme, MD3LightTheme, configureFonts } from 'react-native-paper';

// Configuration des polices
const fontConfig = {
  displayLarge: {
    fontFamily: 'System',
    fontSize: 57,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'System',
    fontSize: 45,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontSize: 32,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontSize: 28,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'System',
    fontSize: 22,
    fontWeight: '500' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '500' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'System',
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '400' as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};

// Thème clair basé sur vuetify.ts
export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#2e7d32',
    onPrimary: '#ffffff',
    primaryContainer: '#a5d6a7',
    onPrimaryContainer: '#1b5e20',
    secondary: '#26a69a',
    onSecondary: '#ffffff',
    secondaryContainer: '#80cbc4',
    onSecondaryContainer: '#00897b',
    tertiary: '#ff6f00',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ffcc80',
    onTertiaryContainer: '#e65100',
    error: '#d32f2f',
    onError: '#ffffff',
    errorContainer: '#ffcdd2',
    onErrorContainer: '#b71c1c',
    background: '#f8fdf9',
    onBackground: '#0d1f0d',
    surface: '#ffffff',
    onSurface: '#1a1a1a',
    surfaceVariant: '#e8f5e9',
    onSurfaceVariant: '#37474f',
    outline: '#bdbdbd',
    outlineVariant: '#a5d6a7',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#1a1a1a',
    inverseOnSurface: '#f5f5f5',
    inversePrimary: '#69f0ae',
    elevation: {
      level0: '#ffffff',
      level1: '#f5f5f5',
      level2: '#eeeeee',
      level3: '#e0e0e0',
      level4: '#bdbdbd',
      level5: '#9e9e9e',
    },
    surfaceDisabled: 'rgba(26, 26, 26, 0.12)',
    onSurfaceDisabled: 'rgba(26, 26, 26, 0.38)',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: configureFonts({ config: fontConfig }),
};

// Thème sombre basé sur vuetify.ts
export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#69f0ae',
    onPrimary: '#003d1a',
    primaryContainer: '#00e676',
    onPrimaryContainer: '#b9f6ca',
    secondary: '#18ffff',
    onSecondary: '#002e33',
    secondaryContainer: '#00e5ff',
    onSecondaryContainer: '#84ffff',
    tertiary: '#ff4081',
    onTertiary: '#4a0013',
    tertiaryContainer: '#f50057',
    onTertiaryContainer: '#ff80ab',
    error: '#ff5252',
    onError: '#2d0000',
    errorContainer: '#ffcdd2',
    onErrorContainer: '#ff5252',
    background: '#0a0e0a',
    onBackground: '#e8f5e9',
    surface: '#121212',
    onSurface: '#f5f5f5',
    surfaceVariant: '#1e1e1e',
    onSurfaceVariant: '#b0bec5',
    outline: '#37474f',
    outlineVariant: '#263238',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#f5f5f5',
    inverseOnSurface: '#1a1a1a',
    inversePrimary: '#2e7d32',
    elevation: {
      level0: '#121212',
      level1: '#1e1e1e',
      level2: '#2a2a2a',
      level3: '#363636',
      level4: '#424242',
      level5: '#4e4e4e',
    },
    surfaceDisabled: 'rgba(245, 245, 245, 0.12)',
    onSurfaceDisabled: 'rgba(245, 245, 245, 0.38)',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: configureFonts({ config: fontConfig }),
};

